### ISSUE TITLE
搭建失败

### ISSUE THREAD

**Issue by aurochs-code** [guanyuxin/baogame#8]
module.js:340
    throw err;
    ^

Error: Cannot find module '../build/Debug/addon'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/games/baogame/node_modules/heapdump/lib/main.js:18:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by guanyuxin** [comment]
npm install 一下试试

**Comment by aurochs-code** [comment]
我是先npm install 然后node app.js报错
[root@iZ11ggxjz2kZ baogame]# npm install
npm WARN package.json fuzion-game@1.0.0 No license field.
[root@iZ11ggxjz2kZ baogame]# node app.js
module.js:340
    throw err;
    ^

Error: Cannot find module '../build/Debug/addon'

[root@iZ11ggxjz2kZ baogame]# node -v
v4.2.4
[root@iZ11ggxjz2kZ baogame]# npm -v
2.14.12

**Comment by vtumi** [comment]
服务器要有编译环境，否则模块会安装失败。

**Comment by guanyuxin** [comment]
看来npm版本最好去掉c相关的

**Comment by waterTraveller** [comment]
问题解决了吗？Error: Cannot find module '../build/Debug/addon'
这个我也遇到了..

**Comment by waterTraveller** [comment]
后来我直接npm install addon,虽然是安装成功了，然后把addon复制到heapdump目录下的新子目录build/Debug/，然后node app.js虽然没报Error: Cannot find module '../build/Debug/addon'这个错，但是又出了新的错误TypeError: addon.configure is not a function。好吧 ，果然我是错的。node.js没玩过，不懂。

**Comment by aurochs-code** [comment]
没有搞定，不知道什么问题。本地能跑起来，服务器上npm install 报错..

**Comment by xieminhui** [comment]
直接cd到baogame目录，重装npm install heapdump
